name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Thay 'main' bằng tên nhánh chính của bạn nếu khác (ví dụ: 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền ghi cho GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch toàn bộ lịch sử để có tất cả các nhánh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install # hoặc yarn install

      - name: Build
        run: npm run build # hoặc yarn build

      - name: Deploy to GitHub Pages using worktree
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          # Kiểm tra xem nhánh gh-pages đã tồn tại chưa, nếu chưa thì tạo
          git fetch origin gh-pages:gh-pages --depth=1 || git checkout --orphan gh-pages
          # Tạo worktree cho nhánh gh-pages (nếu chưa tồn tại) hoặc chuyển đến worktree
          if [ -d ".gh-pages" ]; then
            cd .gh-pages
            git checkout gh-pages
          else
            git worktree add --force --detach .gh-pages origin/gh-pages
            cd .gh-pages
          fi
          # Sao chép build vào worktree, --delete để xóa các tệp cũ không còn
          rsync -av --delete --exclude='node_modules' --exclude='.git' ../build/ .
          git add .
          git commit -m "Deploy to GitHub Pages from GitHub Actions"
          git push origin HEAD:gh-pages --force
          cd ..
          git worktree remove --force .gh-pages