name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Thay 'main' bằng tên nhánh chính của bạn nếu khác (ví dụ: 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền ghi cho GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch toàn bộ lịch sử để có tất cả các nhánh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install # hoặc yarn install

      - name: Build
        run: npm run build # hoặc yarn build

      - name: Deploy to GitHub Pages using worktree
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          # Fetch thông tin về tất cả các nhánh từ origin
          git fetch origin --all --depth=1
          # Tạo worktree cho nhánh gh-pages
          git worktree add --force --detach .gh-pages origin/gh-pages
          # Sao chép build vào worktree
          rsync -av --delete --exclude='node_modules' --exclude='.git' build/ .gh-pages/
          cd .gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages from GitHub Actions"
          git push origin HEAD:gh-pages --force
          cd ..
          git worktree remove --force .gh-pages